### ISSUE TITLE
MultiFolderClone skipping lots of files

### ISSUE THREAD

**Issue by theghost970** [Spazzlo/folderclone#31] opened 2019-08-11 19:42 UTC
Good morning!

I tried to copy a huge shared folder to a Team Drive, the folder has subdirectories with lots of files.
MultiFolderClone copied ~9000 files but skipped nearly 6000 others.
all the files are sized 500 MB+ (avg size is 1.5 GB for each file)

**Comment by Mz49** [comment] 2019-08-12 09:26
Duplicate of #23

**Closed by Mz49** 2019-08-12 09:26 UTC
