### ISSUE TITLE
Too many files lost

### ISSUE THREAD

**Issue by yuritry** [Spazzlo/folderclone#51] opened 2019-09-30 01:23 UTC
Folderclone is a great job. But when I used it to clone folders from shared folders to group folder, there were too many files lost.

**Comment by Mz49** [comment] 2019-09-30 06:09
Try with the newly pushed code.

**Comment by eXhumer** [comment] 2019-09-30 09:58
After extensively testing the new code, I can say that no files are dropped anymore with the latest scripts. Unless, the issue is with latest script, I am going to close this issue.

**Closed by eXhumer** 2019-09-30 09:58 UTC

**Comment by yuritry** [comment] 2019-10-01 15:42
Great job!
Thank you.
