### ISSUE TITLE
multifolderclone issue

### ISSUE THREAD

**Issue by ydleii** [Spazzlo/folderclone#63] opened 2019-10-03 09:06 UTC
getting this error when trying to clone a folder.

C:\Users\prond\AppData\Local\Programs\Python\Python37\Scripts>python multifolderclone.py -s 1GWCcA7cuawKQ8r5jgeJu0zKu2Z4li8Wq -d 1PR5XjJ4XB0-GuH0RwbZfGbfjoCyXoV_-
Traceback (most recent call last):
  File "multifolderclone.py", line 295, in <module>
    main()
  File "multifolderclone.py", line 291, in main
    args.width
  File "multifolderclone.py", line 237, in multifolderclone
    check = build("drive", "v3", credentials=Credentials.from_service_account_file(accounts[0]))
IndexError: list index out of range

Also is there a readme on how to start over completely?  I've tried the remove.py but get an error when i run that also.

C:\Users\prond\AppData\Local\Programs\Python\Python37\Scripts>python remove.py --saf/-d
usage: remove.py [-h] [--token TOKEN] [--credentials CREDENTIALS]
                 (--prefix PREFIX | --suffix SUFFIX | --role ROLE) --drive-id
                 DRIVE_ID
remove.py: error: the following arguments are required: --drive-id/-d

**Comment by Mz49** [comment] 2019-10-03 15:22
Duplicate of #62

**Comment by Mz49** [comment] 2019-10-03 15:23
@ydleii As for remove.py, just as the error says, you need to provide the drive id from which to remove users from.

**Closed by Mz49** 2019-10-03 15:23 UTC

**Comment by Mz49** [comment] 2019-10-03 15:24
@ydleii And actually, there's user error somewhere. It's not finding anything inside the accounts folder. I'll add error handling for this, but there isn't anything in your `accounts` folder.
